### PR TITLE
Improve Context Log highlighting and UI.

### PR DESCRIPTION
**Pull request by cjcenizal**
Improve Context Log highlighting and UI.

### CODE REVIEW

**Comment by epixa** [comment]
Why's this targeting a feature branch rather than upstream?  It doesn't seem to be related to that feature branch, at least.

**Comment by cjcenizal** [comment]
@epixa The original goal was to improve the log context view that Felix is working on, but this view is related to that one, so one thing led to another, and I ended up working on this component first. I'm going to make sure this view's improvements can be carried forward into the log context view, and then I can break out the general table improvements into a separate PR targeting master, if need be.

**Comment by cjcenizal** [comment]
## Comments from UI Review

### Highlighting

Searching for a value, e.g. `MX`, should pull the matching highlighted property to the beginning of the list, so the user doesn't need to scroll to it.

### Performance

* Some users have documents with thousands of fields, so we should test the performance and the UX of this view with similar conditions.
* If performance is bad, maybe truncating the number of displayed fields is an option?
* Feature idea: allow the user to specify the order in which they'd like `_source` fields to be displayed. This will aid scanning for the things they are interested in.

### Reporting

Test it and make sure the PDF looks correct.

### Scrolling

It's a big usability boost if the horizontal scroll is locked for all the documents, so you can scroll them together.

**Comment by cjcenizal** [comment]
I've made some changes to the layout and appearance of the Context view:

* Moved the controls out of the header and into the view itself, in anticipation of our header redesign. In the new design, this is the appropriate place for these kinds of controls.
* Changed the highlight color to the light blue color we're going to use for our "selected item" style in menus and dropdowns.

image

**Comment by weltenwort** [comment]
Wow, I like how orderly it looks now! :+1: And the highlighting work well too. Here are few more thoughts though:

* The padding of the time column now looks out of sync with the _source field. I'll take a look at that.
* I can see the reasoning for moving the size picker near the buttons. But now the whole inline input row somehow looks like it's hanging in empty space there.
* The performance might improve further when the table is rendered using normal angular templates instead of manual dom manipulation. I was hoping to get a chance to clean that up after the context view PR has been merged.

**Comment by weltenwort** [comment]
Moving to the meta level, I'm not certain these extensive changes in the doc table are appropriate in the scope of the context PR. The impact on the main discover table is quite extensive. @uboness has expressed reservations in that regard too. Maybe we should break out the table changes in a separate PR to master?

**Comment by weltenwort** [comment]
Would you mind giving me permission to update this PR?

**Comment by cjcenizal** [comment]
@weltenwort Good point about pulling out the changes to the doc table. I've created https://github.com/elastic/kibana/pull/9798 to make those changes, and I'll revert the commits in this PR.

**Comment by cjcenizal** [comment]
@weltenwort Could you take another look? I refactored the ContextSizePicker directive, and polished the UI a bit. I also removed the "fading effect" from the doc table because it looked weird against the blue background of the highlighted row. I think it also looked weird in general. This affects the Discover app, too. @alt74 what do you think?

Here's what it looks like now:

#### Loading state

image

#### Table

image

**Comment by weltenwort** [comment]
How about we re-use the ToolBar already implemented in the ui framework? Would that be too heavy-weight?

image

**Comment by cjcenizal** [comment]
@weltenwort I was thinking about it but I do think it is a bit too heavy-weight. It's also designed specifically for use with the ToolBarFooter, which doesn't seem appropriate here since the controls at the top and bottom complement/mirror each other in our use case, but the controls in the ToolBarFooter should be a mostly subset of those in the ToolBar.

**Pull request merged**
